$(document).ready(function(){
	$("#mazeBlock2").mouseover(function(){
	  $("#modalGameOver").fadeIn('slow');
	});
	$("#mazeBlock3").mouseover(function(){
	  $("#modalGameOver").fadeIn('slow');
	});
	$("#mazeBlock4").mouseover(function(){
	  $("#modalGameOver").fadeIn('slow');
	});
	$("#mazeBlock5").mouseover(function(){
	  $("#modalGameOver").fadeIn('slow');
	});
	$("#mazeBlock6").mouseover(function(){
	  $("#modalGameOver").fadeIn('slow');
	});
	$("#mazeBlock7").mouseover(function(){
	  $("#modalGameOver").fadeIn('slow');
	});
	$("#mazeBlock8").mouseover(function(){
	  $("#modalGameOver").fadeIn('slow');
	});

	$('#butt').click(function(){
		$("#modalGameOver").fadeOut('slow');
		$(".maze-container").fadeOut('slow');
		setTimeout(window.location.reload.bind(window.location), 700);
	});
});
